services:
  app:
    image: z2z63/event_planning_system:latest
    ports:
      - 127.0.0.1:3000:3000
    environment:
      SECRET: ${SECRET}
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/event_planning_system?schema=public
      NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
    volumes:
      - initdb:/docker-entrypoint-initdb.d/
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: event_planning_system
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - initdb:/docker-entrypoint-initdb.d/
volumes:
  postgres-data:
  initdb: